const wordData = [
  { word: "翻", meaning: "to flip; to turn over; to browse; to look up", example: "我喜歡在書店翻書。(I like to browse books in bookstores.)" },
  { word: "頁", meaning: "page", example: "請翻到這一頁。(Please turn to this page.)" },
  { word: "三明治", meaning: "sandwich", example: "我中午吃了一個三明治。(I ate a sandwich for lunch.)" },
  { word: "門", meaning: "door; gate; classifier for courses or subjects", example: "這棟大樓有三個門。(This building has three entrances.)" },
  { word: "課堂", meaning: "class; classroom instruction; class session", example: "他在課堂上很認真聽講。(He listens carefully in class.)" },
  { word: "期末", meaning: "end of term; final period", example: "期末考快到了，大家都在準備。(Final exams are coming soon.)" },
  { word: "口試", meaning: "oral exam", example: "這門課有期末口試。(This course has a final oral exam.)" },
  { word: "篇", meaning: "measure word for articles or essays", example: "老師要我們寫一篇作文。(The teacher asked us to write an essay.)" },
  { word: "作文", meaning: "composition; essay", example: "這次作文的題目不難。(The topic of this essay is not difficult.)" },
  { word: "用功", meaning: "hardworking; diligent (in studying)", example: "他最近讀書很用功。(He has been studying very hard lately.)" },
  { word: "當", meaning: "to be; to serve as (a role or job)", example: "他將來想當老師。(He wants to be a teacher in the future.)" },
  { word: "修", meaning: "to take or study (a course)", example: "我下學期要修三門課。(I will take three courses next semester.)" },
  { word: "教授", meaning: "professor", example: "這位教授教學經驗豐富。(This professor has rich teaching experience.)" },
  { word: "知識", meaning: "knowledge", example: "閱讀可以增加知識。(Reading can increase knowledge.)" },
  { word: "豐富", meaning: "rich; abundant", example: "他的生活經驗很豐富。(His life experience is very rich.)" },
  { word: "教法", meaning: "teaching method; pedagogy", example: "這位老師的教法很特別。(This teacher’s teaching method is very unique.)" },
  { word: "系", meaning: "department (in a school or university)", example: "他是中文系的學生。(He is a student in the Chinese department.)" },
  { word: "文法", meaning: "grammar", example: "這一課的文法有點難。(The grammar in this lesson is a bit difficult.)" },
  { word: "筆試", meaning: "written exam", example: "這門課有筆試和口試。(This course has a written exam and an oral exam.)" },
  { word: "交", meaning: "to hand in; to submit", example: "請記得準時交作業。(Please remember to submit your homework on time.)" },
  { word: "報告", meaning: "report; presentation", example: "下週我們要做期末報告。(We have to give a final report next week.)" },
  { word: "認真", meaning: "serious; earnest; conscientious", example: "她做事非常認真。(She is very serious about her work.)" },
  { word: "字典", meaning: "dictionary", example: "不會的字可以查字典。(You can look up unfamiliar words in a dictionary.)" },
  { word: "翻", meaning: "to look up (in a dictionary or book)", example: "遇到生字時可以翻字典。(You can look it up in the dictionary when you see a new word.)" },
  { word: "題", meaning: "question; problem (on a test or exam)", example: "這道題目不難。(This question is not difficult.)" },
  { word: "努力", meaning: "to work hard; to make an effort", example: "只要努力，就會有進步。(As long as you work hard, you will improve.)" },
  { word: "能力", meaning: "ability; capability", example: "他的語言能力很強。(His language ability is very strong.)" },
  { word: "將來", meaning: "in the future", example: "我將來想出國留學。(I want to study abroad in the future.)" },
  { word: "夠", meaning: "enough; sufficient", example: "這些錢夠用了。(This amount of money is enough.)" },
  { word: "加油", meaning: "to encourage; to cheer up", example: "考試快到了，加油！(The exam is coming—keep it up!)" },
  { word: "義大利", meaning: "Italy", example: "他去年去義大利旅行。(He traveled to Italy last year.)" },
  { word: "期末考", meaning: "final exam", example: "期末考結束後可以放假了。(After final exams, we can have a break.)" },
  { word: "翻", meaning: "to flip over; to turn (a page)", example: "請把這一頁翻過去。(Please turn this page over.)" }
];
